# ANSIBLE ROLE
# Save the roles in /etc/ansible/roles directory
# Modify the ansible configuration file & add the roles_path in it
# sudo echo "roles_path    = /etc/ansible/roles" >> /etc/ansible/ansible.cfg

# vi jenkins-role.yaml
---
- name: Installing Jenkins using Ansible Roles
  hosts: webservers
  become: true
  roles:
    - jenkins-setup
...

# Place the role in your "roles" directory, and run the playbook with:
# ansible-playbook -i inventory jenkins-playbook.yml

# Set the ansible roles path in ansible configuration file 
