apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "echo 'Preparing the environment...'; sleep 10"]
  containers:
  - name: main-container
    image: nginx
    ports:
    - containerPort: 80
