# ---------------------------------
# REPLICATION-CONTROLLER MANIFEST
# ---------------------------------

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
...

# ------------
# COMMANDS
# ------------
kubectl apply -f rc.yaml                #(to create replication-controller from the above manifest)
kubectl get rc                          #(to see list of pods)
kubectl describe rc nginx               #(to get details of rc)

pods=$(kubectl get pods --selector=app=nginx --output=jsonpath={.items..metadata.name})
echo $pods                              #(to get the list of pods)
