---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "*/1 * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-container
            image: busybox
            command: ["sh", "-c", "echo Hello, Good Morning! && sleep 10"]
          restartPolicy: OnFailure
...

# Commands
# kubectl apply -f cronjob.yaml
# kubectl get cronjob -w                  # to watch the live cronjobs
# kubectl get pods                        # to get the pods
# kubectl logs <pod-name>                 # check the pod logs
# Wait for 5 mins to check the cronjobs
