# ----------------
# SERVICE
# ----------------
# Filename: service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    name: my-pod1
  ports:
    - protocol: TCP
      port: 3001            # Port exposed to the outside world (Load Balancer)
      targetPort: 80        # Port inside the container
...

# Commands
# kubectl apply -f service.yaml
# kubectl get service                #(take a note of the Node-Port)

# Access the application from the browser, using "EC2-Node-PublicIP:<Node-Port>"
